### ISSUE TITLE
FATAL EXCEPTION: main cancelling or entering wrong password for OpenKeychain

### ISSUE THREAD

**Issue by 532910** [DDoSolitary/OkcAgent#10]
```
07-27 00:17:34.072 30468 30468 D AndroidRuntime: Shutting down VM
07-27 00:17:34.075 30468 30468 E AndroidRuntime: FATAL EXCEPTION: main
07-27 00:17:34.075 30468 30468 E AndroidRuntime: Process: org.ddosolitary.okcagent, PID: 30468
07-27 00:17:34.075 30468 30468 E AndroidRuntime: java.lang.RuntimeException: Unable to start service org.ddosolitary.okcagent.ssh.SshAgentService@5d565f3 with Intent { act=org.ddosolitary.okcagent.action.RESULT_CALLBACK cmp=org.ddosolitary.okcagent/.ssh.SshAgentService (has extras) }: java.lang.NullPointerException
07-27 00:17:34.075 30468 30468 E AndroidRuntime: 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3724)
07-27 00:17:34.075 30468 30468 E AndroidRuntime: 	at android.app.ActivityThread.access$1600(ActivityThread.java:200)
07-27 00:17:34.075 30468 30468 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1688)
07-27 00:17:34.075 30468 30468 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
07-27 00:17:34.075 30468 30468 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
07-27 00:17:34.075 30468 30468 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6718)
07-27 00:17:34.075 30468 30468 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-27 00:17:34.075 30468 30468 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
07-27 00:17:34.075 30468 30468 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
07-27 00:17:34.075 30468 30468 E AndroidRuntime: Caused by: java.lang.NullPointerException
07-27 00:17:34.075 30468 30468 E AndroidRuntime: 	at java.util.Objects.requireNonNull(Objects.java:203)
07-27 00:17:34.075 30468 30468 E AndroidRuntime: 	at java.util.concurrent.ArrayBlockingQueue.put(ArrayBlockingQueue.java:332)
07-27 00:17:34.075 30468 30468 E AndroidRuntime: 	at org.ddosolitary.okcagent.AgentService.onStartCommand(AgentService.kt:117)
07-27 00:17:34.075 30468 30468 E AndroidRuntime: 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3705)
07-27 00:17:34.075 30468 30468 E AndroidRuntime: 	... 8 more
07-27 00:17:34.098  2628  2714 W libprocessgroup: kill(-24721, 9) failed: No such process
07-27 00:17:34.113  2160  2160 I Zygote  : Process 24721 exited due to signal (9)
07-27 00:17:34.137  2628  2714 W libprocessgroup: kill(-24721, 9) failed: No such process
07-27 00:17:34.137  2628  2714 I libprocessgroup: Successfully killed process cgroup uid 10247 pid 24721 in 176ms
```

**Comment by DDoSolitary** [comment]
It seems that the crash is caused by the fact that ArrayBlockingQueue doesn't support putting null values into it.

**Comment by 532910** [comment]
I confirm it doesn't crashes more, but it waits forever #12
