### ISSUE TITLE
FATAL EXCEPTION: main on two requests

### ISSUE THREAD

**Issue by 532910** [DDoSolitary/OkcAgent#23]
Steps to reproduce:
1. Start two ssh clients
2. Wait for two notifications to be shown
3. Tap the first one

```
FATAL EXCEPTION: main
Process: org.ddosolitary.okcagent, PID: 17710
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.ddosolitary.okcagent/org.ddosolitary.okcagent.IntentRunnerActivity}: android.content.IntentSender$SendIntentException
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
Caused by: android.content.IntentSender$SendIntentException
        at android.app.Activity.startIntentSenderForResultInner(Activity.java:5471)
        at android.app.Activity.startIntentSenderForResult(Activity.java:5439)
        at androidx.fragment.app.FragmentActivity.startIntentSenderForResult(FragmentActivity.java:704)
        at android.app.Activity.startIntentSenderForResult(Activity.java:5406)
        at androidx.fragment.app.FragmentActivity.startIntentSenderForResult(FragmentActivity.java:689)
        at org.ddosolitary.okcagent.IntentRunnerActivity.processIntent(IntentRunnerActivity.kt:30)
        at org.ddosolitary.okcagent.IntentRunnerActivity.onCreate(IntentRunnerActivity.kt:46)
        at android.app.Activity.performCreate(Activity.java:7824)
        at android.app.Activity.performCreate(Activity.java:7813)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        ... 11 more
```

**Comment by DDoSolitary** [comment]
What's the version of app you're using? The error message seems identical to DDoSolitary/okc-agents#1, which has already been fixed. If I did the fix correctly, the second notification should not appear until you've tapped and handled the first one.

**Comment by 532910** [comment]
version 0.2.0
I was pretty sure #1 was fixed, but actually it still fails, and this one is a dup of #1.

**Comment by DDoSolitary** [comment]
Please try v0.2.2, which is the latest releasee and also the first release that contians the fix.

**Comment by 532910** [comment]
The latest 0.2.2 works fine.
