### ISSUE TITLE
Crashes after tapping the notification for authorization.

### ISSUE THREAD

**Issue by edward-p** [DDoSolitary/OkcAgent#6]
Command line utilities version: r23 from bintray
APP version: r74 from bintray.
logcat:
```
05-30 19:36:25.234  1131  1883 I ActivityTaskManager: START u0 {act=org.ddosolitary.okcagent.action.RUN_PENDING_INTENT flg=0x10000000 cmp=org.ddosolitary.okcagent/.IntentRunnerActivity (has extras)} from uid 10377
05-30 19:36:25.258  1131  1131 V SettingsProvider: Notifying for 0: content://settings/secure/reminder_exp_learning_time_elapsed
05-30 19:36:25.211  2142  2142 W HeadsUpManagerPhone: onHeadsUpPinnedModeChanged
05-30 19:36:25.257 12235 12235 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@631e8ac
05-30 19:36:25.348 12235 12235 D AndroidRuntime: Shutting down VM
05-30 19:36:25.349 12235 12235 E AndroidRuntime: FATAL EXCEPTION: main
05-30 19:36:25.349 12235 12235 E AndroidRuntime: Process: org.ddosolitary.okcagent, PID: 12235
05-30 19:36:25.349 12235 12235 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.ddosolitary.okcagent/org.ddosolitary.okcagent.IntentRunnerActivity}: android.content.IntentSender$SendIntentException
05-30 19:36:25.349 12235 12235 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
05-30 19:36:25.349 12235 12235 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
05-30 19:36:25.349 12235 12235 E AndroidRuntime:        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
05-30 19:36:25.349 12235 12235 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
05-30 19:36:25.349 12235 12235 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
05-30 19:36:25.349 12235 12235 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
05-30 19:36:25.349 12235 12235 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:107)
05-30 19:36:25.349 12235 12235 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:214)
05-30 19:36:25.349 12235 12235 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7356)
05-30 19:36:25.349 12235 12235 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
05-30 19:36:25.349 12235 12235 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
05-30 19:36:25.349 12235 12235 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
05-30 19:36:25.349 12235 12235 E AndroidRuntime: Caused by: android.content.IntentSender$SendIntentException
05-30 19:36:25.349 12235 12235 E AndroidRuntime:        at android.app.Activity.startIntentSenderForResultInner(Activity.java:5471)
05-30 19:36:25.349 12235 12235 E AndroidRuntime:        at android.app.Activity.startIntentSenderForResult(Activity.java:5439)
05-30 19:36:25.349 12235 12235 E AndroidRuntime:        at androidx.fragment.app.FragmentActivity.startIntentSenderForResult(FragmentActivity.java:705)
05-30 19:36:25.349 12235 12235 E AndroidRuntime:        at android.app.Activity.startIntentSenderForResult(Activity.java:5406)
05-30 19:36:25.349 12235 12235 E AndroidRuntime:        at androidx.fragment.app.FragmentActivity.startIntentSenderForResult(FragmentActivity.java:690)
05-30 19:36:25.349 12235 12235 E AndroidRuntime:        at org.ddosolitary.okcagent.IntentRunnerActivity.processIntent(IntentRunnerActivity.kt:30)
05-30 19:36:25.349 12235 12235 E AndroidRuntime:        at org.ddosolitary.okcagent.IntentRunnerActivity.onCreate(IntentRunnerActivity.kt:46)
05-30 19:36:25.349 12235 12235 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:7824)
05-30 19:36:25.349 12235 12235 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:7813)
05-30 19:36:25.349 12235 12235 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
05-30 19:36:25.349 12235 12235 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
05-30 19:36:25.349 12235 12235 E AndroidRuntime:        ... 11 more
05-30 19:36:25.385 12235 12265 I FA      : Tag Manager is not found and thus will not be used
05-30 19:36:25.395  1131 12308 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
05-30 19:36:25.395  1131  2622 W ActivityManager: Process org.ddosolitary.okcagent has crashed too many times: killing!
05-30 19:36:25.395  1131  2622 W ActivityTaskManager:   Force finishing activity org.ddosolitary.okcagent/.IntentRunnerActivity
05-30 19:36:25.401 12235 12291 D NetworkSecurityConfig: No Network Security Config specified, using platform default
05-30 19:36:25.403  1131  2622 I ActivityManager: Killing 12235:org.ddosolitary.okcagent/u0a377 (adj 0): crash
05-30 19:36:25.405  1131  2622 W ActivityManager: Scheduling restart of crashed service org.ddosolitary.okcagent/.ssh.SshAgentService in 1000ms
```

**Comment by 532910** [comment]
1. I have the same issue on android 9, please update the title.
2. Does it work fine after phone reboot?

**Comment by DDoSolitary** [comment]
Thanks for the report. I'll investigate it this summer vacation (which begins in July)

**Comment by 532910** [comment]
I've downgraded to r73 and it works fine for me.

**Comment by edward-p** [comment]
> 1. I have the same issue on android 9, please update the title.
> 2. Does it work fine after phone reboot?

It only works once after a reboot, then crashes every time.

**Comment by 532910** [comment]
> It only works once after a reboot, then crashes every time.

So, yep, I have the same issue with r74.

**Comment by 532910** [comment]
@DDoSolitary, BTW, r73 has no annoying notifications and just pop-ups the passphrase prompt.

**Comment by edward-p** [comment]
> @DDoSolitary, BTW, r73 has no annoying notifications and just pop-ups the passphrase prompt.

But it only works on Android 9 or lower. Since Android 10 doesn't allow starting activities from background.

**Comment by DDoSolitary** [comment]
It seems that r74 is built from the `android-10` branch that I'm still working on. So the crashing behavior is known and something I'm still trying to fix. I just forgot to prevent CI from uploading built package from other branches.

The fact that r73 doesn't work on Android 10 is also known, and this is why I created the `android-10` trying to fix it.

**Comment by 532910** [comment]
F-Droid version doesn't require to tap notification and works fine.

**Comment by ralsei** [comment]
Can confirm that this happens on Android 10, and F-Droid/r73 does not work on Android 10.

**Comment by DDoSolitary** [comment]
It should have been fixed in the [latest dev build](https://dl.bintray.com/ddosolitary/dev-releases/OkcAgent/:OkcAgent-v0.2.0-50-g9697237.apk)

**Comment by ralsei** [comment]
Can confirm.

**Comment by edward-p** [comment]
confirmed +1

**Comment by 532910** [comment]
ack
